### ISSUE TITLE
Using single quotes in a tag

### ISSUE THREAD

**Issue by nochso** [jralph/Twig-Markdown#1]
Hi! I found this while using the markdown tag:

```
{% markdown %}let's cause a parse error{% endmarkdown %}
```

will cause this error:

> PHP Parse error:  syntax error, unexpected 's' (T_STRING) in /home/amblin/dev/web/benchmark/vendor/twig/twig/lib/Twig/Environment.php(390) : eval()'d code on line 211

Apparently `$content` isn't escaped when being compiled by `\Jralph\Twig\Markdown\Node`.
I'm not that experienced in extending Twig, but couldn't you assign the node's data directly?

**Comment by jralph** [comment]
Thanks. I'll have a look into this and create a test for it and see if I
can get it sorted.

**Comment by nochso** [comment]
Already gave it a try :)

Let me know what you think.

**Comment by jralph** [comment]
Seems good to me. Many thanks!
