### ISSUE TITLE
twig-markdown can also be updated?

### ISSUE THREAD

**Issue by Open343** [jralph/Twig-Markdown#3]
It's two years. This program will be updated? Thank you!

**Comment by jralph** [comment]
I'll update it when I get a chance. I haven't been using it myself so was unaware of any bugs. Feel free to make a pull request if you have any changes.

**Comment by jralph** [comment]
Or if you can let me know what's broken exactly I'll look at getting it fixed for you.

**Comment by jralph** [comment]
Just noticed that there is now twig 2.0.

I have gone through the package and updated everything to work with twig 2.0.
